services:
  mongo:
    image: mongo
    restart: on-failure
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: aveen
    #   MONGO_INITDB_ROOT_PASSWORD: mops
    ports:
      - "27017:27017"
    networks:
      - mops
    depends_on:
      - rabbitmq
      

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: on-failure
    networks:
      - mops

  data_simulator:
    build: 
      context: ./data_simulator
    depends_on:
      - iot_controller
    networks:
      - mops
  iot_controller:
    build: 
      context: ./iot_controller
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - mops
  #     - rabbitmq
networks:
  mops:
    driver: bridge
