services:
  mongo:
    image: mongo
    restart: on-failure
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: aveen
    #   MONGO_INITDB_ROOT_PASSWORD: mops
    ports:
      - "27017:27017"
    networks:
      - mops
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: on-failure
    networks:
      - mops

  data_simulator:
    build: 
      context: ./data_simulator
    depends_on:
      - iot_controller
    restart: always
    ports:
      - "8070:8070"
    networks:
      - mops
  iot_controller:
    build: 
      context: ./iot_controller
    ports:
      - "5000:5000"
    restart: on-failure
    
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - mops
  #     - rabbitmq
  rule_engine:
    build:
      context: ./rule_engine
    restart: always
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: sync+restart
          path: .
          target: .
    depends_on:
      - iot_controller
    networks:
      - mops 
networks:
  mops:
    driver: bridge
